[package]
name = "embedder"
version = "0.1.1"
edition = "2021"
description = "Get basic website information with ease."
license = "MIT"
repository = "https://github.com/tascord/embedder"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.75"
reqwest = "0.11.22"
scraper = "0.18.1"
to_and_fro = "0.4.0"
tokio = { version = "1.35.0", features = ["full"] }
url = "2.5.0"
