[package]
name = "embedder"
version = "0.3.0"
edition = "2021"
description = "Get basic website information with ease."
license = "MIT"
repository = "https://github.com/tascord/embedder"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-process = "2.0.1"
fantoccini = "0.19.3"
futures = "0.3.29"
lazy_static = "1.4.0"
reqwest = "0.11.22"
scraper = "0.18.1"
serde = { version = "1.0.193", features = ["derive"] }
tokio = { version = "1.35.0", features = ["sync", "rt"] }
url = "2.5.0"
which = "5.0.0"

[dev-dependencies]
tokio = { version = "1.35.0", features = ["sync", "rt", "macros"] }