[package]
name = "embedder"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.75"
cosmic-text = "0.10.0"
fontdue = "0.8.0"
hex_color = "3.0.0"
reqwest = "0.11.22"
scraper = "0.18.1"
tiny-skia = "0.11.3"
to_and_fro = "0.4.0"
tokio = { version = "1.35.0", features = ["full"] }
url = "2.5.0"
